sudo: required
dist: trusty
language: node_js
node_js:
  - '4.2'

notifications:
  email: false

before_install:
- if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

install:
- npm install

before_script:

script:
- npm run lint
- npm test

after_script:
- npm run build
