sudo: required
dist: trusty
language: node_js
node_js:
  - '4.4.6'

notifications:
  email: false

before_install:
- npm i -g npm@3.10.9

install:
- npm install

before_script:

script:
- npm run lint
- npm test

after_script:
- npm run build
